// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWTCC3uexp6nxuv-HQd6E-_J72Z1W9Cwg',
    appId: '1:874287673860:web:494b7a7663622fd9923b51',
    messagingSenderId: '874287673860',
    projectId: 'apricity-afe56',
    authDomain: 'apricity-afe56.firebaseapp.com',
    storageBucket: 'apricity-afe56.firebasestorage.app',
    measurementId: 'G-SLJF19JJ9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhsvcReQlL4OKFwHypUFTYDSeV7XiYjHk',
    appId: '1:874287673860:android:b7f8884fe1d75cab923b51',
    messagingSenderId: '874287673860',
    projectId: 'apricity-afe56',
    storageBucket: 'apricity-afe56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArbc8WZ-DrJJYzmQGnO4is68TmslKWBd8',
    appId: '1:874287673860:ios:99957f23992963e2923b51',
    messagingSenderId: '874287673860',
    projectId: 'apricity-afe56',
    storageBucket: 'apricity-afe56.firebasestorage.app',
    iosBundleId: 'com.arthurchan.apricity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArbc8WZ-DrJJYzmQGnO4is68TmslKWBd8',
    appId: '1:874287673860:ios:254117c47e2e7281923b51',
    messagingSenderId: '874287673860',
    projectId: 'apricity-afe56',
    storageBucket: 'apricity-afe56.firebasestorage.app',
    iosBundleId: 'com.example.apricity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWTCC3uexp6nxuv-HQd6E-_J72Z1W9Cwg',
    appId: '1:874287673860:web:198f92c650b408e0923b51',
    messagingSenderId: '874287673860',
    projectId: 'apricity-afe56',
    authDomain: 'apricity-afe56.firebaseapp.com',
    storageBucket: 'apricity-afe56.firebasestorage.app',
    measurementId: 'G-BW5PZ4KLMZ',
  );
}
